name: Build EXE

on:
  release:
    types: [created]

jobs:
  build_and_publish_exe:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: pip install poetry
    - run: poetry install
    - run: poetry run pyinstaller console-app.spec
    - run: gh release upload ${{ github.event.release.tag_name }} dist\Tungeon.exe
      env:
        GH_TOKEN: ${{ github.token }}